spring.cloud.gateway.rsocket.client:
  route-id: 3
  service-name: pong
  tags:
    INSTANCE_NAME: pong
  broker:
    host: localhost
    port: 7002

server:
  port: 0

logging:
  level:
    org.springframework.messaging.rsocket: INFO
