spring.cloud.gateway.rsocket.client:
  route-id: 3
  service-name: responder
  tags:
    INSTANCE_NAME: responder
  broker:
    host: localhost
    port: 7002

server:
  port: 0

logging:
  level:
    org.springframework.messaging.rsocket: INFO
