spring.cloud.gateway.rsocket.client:
  route-id: 1
  service-name: requester
#  tags:
#    INSTANCE_NAME: ping1
#  forwarding:
#    pong-rc:
#      service_name: pong
  broker:
    host: localhost
    port: 7002

server:
  port: 0
#debug: true